README.md
https://github.com/camunda/camunda-bpm-platform/issues/4988
=> chore(README): extend how to use

.github/actions/setup-maven/action.yml, .github/workflows/ci.yml, .github/workflows/release-c7-data-migrator.yml
* setup-maven: add mirror/server parsing
* rename inputs
* add skip tests to prepare release
* resolve inputs correctly
related to https://github.com/camunda/camunda-bpm-platform/issues/4990
=> chore(ci): add maven central server

core/src/main/java/io/camunda/migrator/config/RdbmsConfiguration.java, pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/5133
=> chore(core): adopt latest changes from rdbms

assembly/assembly.xml, assembly/resources/start.sh, core/src/main/java/io/camunda/migrator/AutoDeployer.java, core/src/main/java/io/camunda/migrator/RuntimeMigrator.java, core/src/main/java/io/camunda/migrator/config/MigratorAutoConfiguration.java, distro/src/main/java/io/camunda/migrator/app/MigratorApp.java, qa/src/test/java/io/camunda/migrator/qa/AutoDeploymentIT.java, qa/src/test/java/io/camunda/migrator/qa/RuntimeMigrationAbstractTest.java, qa/src/test/resources/my-resources/simpleProcess.bpmn
related to camunda/camunda-bpm-platform#5156
=> feat(distro): allow C8 resource auto-deployment

core/src/main/java/io/camunda/migrator/RuntimeMigrator.java
related to camunda/camunda-bpm-platform#5176
=> chore(core): remove multi-instance workaround

core/src/main/java/io/camunda/migrator/config/MigratorAutoConfiguration.java
related to camunda/camunda-bpm-platform#5180
=> chore(core): configure uuid generator

core/src/main/java/io/camunda/migrator/history/IdKeyMapper.java, core/src/main/resources/mapper/IdKey.xml, qa/src/test/java/io/camunda/migrator/qa/RuntimeMigrationAbstractTest.java, qa/src/test/java/io/camunda/migrator/qa/SampleRuntimeMigrationTest.java
Picking cleanup mechanism from pagination branch
related to https://github.com/camunda/camunda-bpm-platform/issues/4996
=> feat(IT): add cleanup mechanism for tests

README.md, qa/src/test/java/io/camunda/migrator/qa/MessageEventMigrationTest.java, qa/src/test/resources/io/camunda/migrator/bpmn/c7/messageCatchEventProcess.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c8/messageCatchEventProcess.bpmn
Based on 5166-task-tests, so not to be merged until that one is.  Only the latest commit is relevant, the rest I will drop/rebase once 5166-task-tests is merged
related to https://github.com/camunda/camunda-bpm-platform/issues/5165
=> chore(IT): add tests for message events

README.md, qa/src/test/java/io/camunda/migrator/qa/GatewayMigrationTests.java, qa/src/test/resources/io/camunda/migrator/bpmn/c7/eventGateway.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c7/parallelGateway.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c8/eventGateway.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c8/parallelGateway.bpmn
related to  [#5163](https://github.com/camunda/camunda-bpm-platform/issues/5163)
=> chore(qa): add gateway element tests

core/src/main/java/io/camunda/migrator/RuntimeMigrator.java, qa/src/test/java/io/camunda/migrator/qa/SkipAndRetryProcessInstancesTest.java
related to camunda/camunda-bpm-platform#5196
=> fix(core): prevent NPE when process instance has been completed

pom.xml
related to: camunda/camunda-bpm-platform/issues/5161
=> chore(project): pin C7 & C8 dependencies for release

core/src/main/resources/mapper/IdKey.xml
https://github.com/camunda/camunda-bpm-platform/issues/4991
=> chore(core): reuse sql in count and query

core/src/main/java/io/camunda/migrator/Pagination.java, core/src/main/java/io/camunda/migrator/RuntimeMigrator.java, qa/src/test/java/io/camunda/migrator/qa/VariablesTest.java
related to camunda/camunda-bpm-platform#5201
=> fix(core): handle variable with `null` values

assembly/resources/start.bat
https://github.com/camunda/camunda-bpm-platform/issues/5156
=> chore(assembly): add deployment dir to start.bat

README.md
related to[ #5172](https://github.com/camunda/camunda-bpm-platform/issues/5172)
Add small note about deploying all resources (noted while testing business rule tasks without deployed dmn reference)
=> chore(docs): document deploying all required resources

.github/workflows/release.yml
https://github.com/camunda/camunda-bpm-platform/issues/5191
=> revert: daily run of CI

qa/src/test/java/io/camunda/migrator/qa/element/EventSubprocessMigrationTest.java, qa/src/test/java/io/camunda/migrator/qa/element/GatewayMigrationTest.java, qa/src/test/java/io/camunda/migrator/qa/element/TimerElementMigrationTest.java, qa/src/test/resources/io/camunda/migrator/bpmn/c7/timerDurationBoundaryEventProcess.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c8/timerDurationBoundaryEventProcess.bpmn
related to[ #5173](https://github.com/camunda/camunda-bpm-platform/issues/5173)
adds tests for timers with duration
tests with other timer types and docs coming with other PRs
=> chore(IT): add duration timer test

.github/workflows/ci.yml, README.md, core/src/main/resources/mapper/IdKey.xml, qa/pom.xml, qa/src/main/resources/application.yml, qa/src/test/java/io/camunda/migrator/qa/MultiDbAbstractTest.java, qa/src/test/java/io/camunda/migrator/qa/MultiDbExtension.java, qa/src/test/java/io/camunda/migrator/qa/RuntimeMigrationAbstractTest.java, qa/src/test/java/io/camunda/migrator/qa/WithMultiDb.java, qa/src/test/resources/application-oracle.yml, qa/src/test/resources/application-postgresql.yml
Related to https://github.com/camunda/camunda-bpm-platform/issues/5207
```shell
mvn verify               # run tests with h2
mvn verify -Poracle      # run tests with oracle
mvn verify -Ppostgresql  # run tests with postgresql
```
=> feat(test): extends tests for oracle and postgresql

core/src/main/java/io/camunda/migrator/config/RdbmsConfiguration.java, pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/5262
=> chore(release): pin C7 and C8 dependencies for alpha3

README.md, core/src/main/java/io/camunda/migrator/config/MigratorAutoConfiguration.java, core/src/main/java/io/camunda/migrator/impl/DateVariableInterceptor.java, qa/src/test/java/io/camunda/migrator/qa/VariablesTest.java
https://github.com/camunda/camunda-bpm-platform/issues/5244
=> feat(core): add Date variable transformation

core/src/main/java/io/camunda/migrator/config/MigratorAutoConfiguration.java
https://github.com/camunda/camunda-bpm-platform/issues/5271
=> fix(core): Temporarily disable metrics on process engine configuration

core/src/main/java/io/camunda/migrator/config/mybatis/C8Configuration.java, pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/5210
⚠️ To be merged after release
=> chore(release): undo pin dependencies for release alpha-3

core/src/main/java/io/camunda/migrator/history/ConverterUtil.java, core/src/test/java/io/camunda/migrator/history/ConverterUtilTest.java
related to: camunda/camunda-bpm-platform/issues/5001
=> chore(core): update key generation

qa/src/test/java/io/camunda/migrator/qa/element/TimerElementMigrationTest.java, qa/src/test/resources/io/camunda/migrator/bpmn/c7/timerDateCatchProcess.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c8/timerDateCatchProcess.bpmn
related to camunda/camunda-bpm-platform/issues/5173
=> chore(IT): add date timer tests

core/src/main/java/io/camunda/migrator/HistoryMigrator.java
related to [#5260](https://github.com/camunda/camunda-bpm-platform/issues/5260)
- adjusted history migration logic to follow same pagination approach as runtime
- we dont have CI for this yet
- renamed one method I noticed was unclearly named
=> feat(history): add pagination to history migration

core/pom.xml, distro/pom.xml, qa/pom.xml
related to camunda/camunda-bpm-platform#5304
=> chore(*): exclude unneeded third-party deps

core/src/main/java/io/camunda/migrator/constants/MigratorConstants.java, core/src/main/java/io/camunda/migrator/impl/RuntimeValidator.java, core/src/main/java/io/camunda/migrator/impl/logging/RuntimeValidatorLogs.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationAbstractTest.java, qa/src/test/java/io/camunda/migrator/qa/runtime/RuntimeMigrationAbstractTest.java, qa/src/test/java/io/camunda/migrator/qa/runtime/element/AbstractElementMigrationTest.java, qa/src/test/java/io/camunda/migrator/qa/runtime/element/EventSubprocessMigrationTest.java, qa/src/test/java/io/camunda/migrator/qa/runtime/element/GatewayMigrationTest.java, qa/src/test/java/io/camunda/migrator/qa/runtime/element/MessageEventMigrationTest.java, qa/src/test/java/io/camunda/migrator/qa/runtime/element/SubprocessMigrationTest.java, qa/src/test/java/io/camunda/migrator/qa/runtime/element/TimerElementMigrationTest.java, qa/src/test/resources/io/camunda/migrator/bpmn/c7/callActivityProcessNoPropagation.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c7/callActivityProcessNoPropagationWithMapping.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c8/callActivityProcessNoPropagation.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c8/callActivityProcessNoPropagationWithMapping.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c8/callMultiInstanceProcess.bpmn
related to: https://github.com/camunda/camunda-bpm-platform/issues/5299
=> feat(core): validate if propagateAllParentVariables configured

README.md
Context: https://camunda.slack.com/archives/C088ESH34P2/p1753798940509859?thread_ts=1752047330.776359&cid=C088ESH34P2
=> Reflect repo name change in `README`

.github/renovate.json, .github/workflows/renovate-auto-merge.yml
related to camunda/camunda-bpm-platform#5317
=> chore(.github): automatically merge dependency updates

.github/workflows/renovate-auto-merge.yml
related to camunda/camunda-bpm-platform#5317
=> chore(wrkflw/auto-merge): remove label check

core/src/main/java/io/camunda/migrator/HistoryMigrator.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationSkippingTest.java
related to: camunda/camunda-bpm-platform/issues/5325
=> chore(qa): HistoryMigrationSkippingTest refactor logLevel cfg

renovate.json
The renovate config was duplicated:
- ./renovate.json
- ./.github/renovate.json
related to camunda/camunda-bpm-platform#5317
=> chore(renovate): remove duplicated config

core/src/main/java/io/camunda/migrator/HistoryMigrator.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationSkippingTest.java
related to: https://github.com/camunda/camunda-bpm-platform/issues/5325
=> chore(qa): add more test for skipping PI

core/src/main/java/io/camunda/migrator/impl/RuntimeValidator.java, core/src/main/java/io/camunda/migrator/impl/util/C7Utils.java, qa/src/test/java/io/camunda/migrator/qa/runtime/SkipAndRetryProcessInstancesTest.java, qa/src/test/resources/io/camunda/migrator/bpmn/c7/multiInstanceServiceTaskProcess.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c8/multiInstanceServiceTaskProcess.bpmn
related to: camunda/camunda-bpm-platform/issues/5300
=> fix(core): should skip multiInstance serviceTasks

README.md, core/src/main/java/io/camunda/migrator/impl/RuntimeValidator.java, core/src/main/java/io/camunda/migrator/impl/logging/RuntimeValidatorLogs.java, qa/src/test/java/io/camunda/migrator/qa/runtime/TenantTest.java, qa/src/test/java/io/camunda/migrator/qa/util/ProcessDefinitionDeployer.java
related to camunda/camunda-bpm-platform#5340
=> chore(core): skip process instances with tenant id

core/src/main/java/io/camunda/migrator/impl/persistence/IdKeyMapper.java, core/src/main/resources/mapper/IdKey.xml, qa/src/test/java/io/camunda/migrator/qa/persistence/IdKeyStartDateMappingTest.java
related to: camunda/camunda-bpm-platform/issues/5339
=> fix(core): add mapper config for IdKeyModel

core/src/main/java/io/camunda/migrator/config/mybatis/C8Configuration.java
related to [failures on main](https://github.com/camunda/camunda-7-to-8-data-migrator/actions/runs/16822455400)
=> fix(c8ConfigCtor): add missing c8 config param

core/src/main/java/io/camunda/migrator/HistoryMigrator.java, core/src/main/java/io/camunda/migrator/RuntimeMigrator.java, core/src/main/java/io/camunda/migrator/impl/clients/C7Client.java, core/src/main/java/io/camunda/migrator/impl/clients/DbClient.java, core/src/main/java/io/camunda/migrator/impl/logging/C7ClientLogs.java, distro/src/main/java/io/camunda/migrator/app/MigratorApp.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationAbstractTest.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationOrderedByStartDateTest.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationRetryTest.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationSkippingTest.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryTaskMigrationTest.java, qa/src/test/java/io/camunda/migrator/qa/runtime/RuntimeMigrationAbstractTest.java, qa/src/test/resources/io/camunda/migrator/bpmn/c7/includeAllSupportedElementsProcess.bpmn
Related to https://github.com/camunda/camunda-bpm-platform/issues/5326
=> feat(history): add retry logic for history

.github/renovate.json, pom.xml
related to camunda/camunda-bpm-platform#5276
=> chore(renovate): avoid bumping to snapshot versions

core/src/main/java/io/camunda/migrator/HistoryMigrator.java, core/src/main/java/io/camunda/migrator/RuntimeMigrator.java, core/src/main/java/io/camunda/migrator/impl/clients/DbClient.java, core/src/main/java/io/camunda/migrator/impl/persistence/IdKeyMapper.java, core/src/main/java/io/camunda/migrator/impl/util/PrintUtils.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationListSkippedTest.java, qa/src/test/java/io/camunda/migrator/qa/runtime/SkipAndRetryProcessInstancesTest.java, qa/src/test/resources/io/camunda/migrator/bpmn/c7/comprehensiveSkippingTestProcess.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c8/comprehensiveSkippingTestProcess.bpmn
related to: camunda/camunda-bpm-platform/issues/5327
=> feat(core): list skipped historicEntities

core/src/main/java/io/camunda/migrator/HistoryMigrator.java, core/src/main/java/io/camunda/migrator/config/mybatis/C8Configuration.java
https://github.com/camunda/camunda-bpm-platform/issues/5276
=> chore(core): adapt latest RDBMS changes from snapshot

README.md, core/src/main/java/io/camunda/migrator/HistoryMigrator.java, core/src/main/java/io/camunda/migrator/impl/persistence/IdKeyMapper.java, distro/src/main/java/io/camunda/migrator/app/MigratorApp.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationAbstractTest.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationListSkippedFilterTest.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationListSkippedTest.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationRetryTest.java, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationSkippingTest.java, qa/src/test/java/io/camunda/migrator/qa/history/SkippedEntitiesLogParserUtils.java, qa/src/test/java/io/camunda/migrator/qa/util/SkippedEntitiesLogParserUtils.java
related to: camunda/camunda-bpm-platform/issues/5327
=> feat(core): enable filtering on history list-skipped

core/src/main/java/io/camunda/migrator/HistoryMigrator.java, core/src/main/java/io/camunda/migrator/impl/logging/HistoryMigratorLogs.java, qa/src/test/java/io/camunda/migrator/qa/history/entity/HistoryDecisionMigrationTest.java
related to [#5307](https://github.com/camunda/camunda-bpm-platform/issues/5307)
I also moved the decision IT into the entities package
=> chore(dmn): add more logging

core/src/main/java/io/camunda/migrator/HistoryMigrator.java, core/src/main/java/io/camunda/migrator/impl/clients/C7Client.java, core/src/main/java/io/camunda/migrator/impl/clients/DbClient.java, core/src/main/java/io/camunda/migrator/impl/logging/DbClientLogs.java, core/src/main/java/io/camunda/migrator/impl/persistence/IdKeyMapper.java, core/src/main/resources/mapper/IdKey.xml, qa/src/test/java/io/camunda/migrator/qa/history/HistoryMigrationOrderedByStartDateTest.java
related to [#5369](https://github.com/camunda/camunda-bpm-platform/issues/5369)
CI is expected to fail as C7 query PR is not yet merged
=> feat(variables): fetch variables based on creationTime

core/src/main/java/io/camunda/migrator/config/mybatis/C8Configuration.java, core/src/main/java/io/camunda/migrator/converter/ProcessInstanceConverter.java, core/src/main/java/io/camunda/migrator/impl/clients/C7Client.java, qa/src/test/java/io/camunda/migrator/qa/history/entity/HistoryProcessInstanceTest.java
https://github.com/camunda/camunda-bpm-platform/issues/5400
=> revert(core): revert incident data for HPI

core/src/main/java/io/camunda/migrator/config/mybatis/C8Configuration.java
=> fix(c8Config): fix correlatedMsg classes

distro/src/main/java/io/camunda/migrator/app/MigratorApp.java, qa/src/test/java/io/camunda/migrator/qa/distribution/DistributionSmokeTest.java
related to [#5426](https://github.com/camunda/camunda-bpm-platform/issues/5426)
=> chore(flags): adjust help flag dialog usage

.github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md, README.md
https://github.com/camunda/camunda-bpm-platform/issues/5139
=> chore(github): add templates

.github/workflows/renovate-auto-merge.yml
=> chore(ci): increase auto-merge delay

core/src/main/java/io/camunda/migrator/impl/RuntimeValidator.java, core/src/main/java/io/camunda/migrator/impl/logging/RuntimeValidatorLogs.java, core/src/main/java/io/camunda/migrator/impl/model/FlowNode.java, core/src/main/java/io/camunda/migrator/impl/util/C7Utils.java, qa/src/test/java/io/camunda/migrator/qa/runtime/SkipAndRetryProcessInstancesTest.java, qa/src/test/java/io/camunda/migrator/qa/runtime/element/GatewayMigrationTest.java, qa/src/test/java/io/camunda/migrator/qa/runtime/variables/VariablesTest.java, qa/src/test/resources/io/camunda/migrator/bpmn/c7/multiInstanceProcess.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c7/multipleStartEvent.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c8/multiInstanceProcess.bpmn, qa/src/test/resources/io/camunda/migrator/bpmn/c8/multipleStartEvent.bpmn
related to: camunda/camunda-bpm-platform/issues/5455
closes #
=> fix(core): skip PI if active gateway
